
######################
# Dataset Parameters #
#######################

# The length of each sample
sequence_length: 10
# The distance between 1's
period: 4

#######################
# Training Parameters #
#######################

# The quantity of steps in the diffusion process
T: 2000
# Quantity of heartbeat sequences per batch
batch_size: 100
# Quantity of batches to train on
num_batches: 5
# Quantity of samples to use when approximating the loss
num_sample_steps: 30
# Quantity of training epochs
epochs: 100
# Learning rate
lr: 0.01

#################
# Miscellaneous #
#################

# Distance between epochs where loss info is printed
training_info_freq: 1